# Python Libraries for Data Science

## Numpy
* NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. 
* Using NumPy, mathematical and logical operations on arrays can be performed


In [1]:
import numpy as np
a=[1,2,3,4,5,6,7,8,8,9] # creating using numpy
np.array(a) # single dimensional array

array([1, 2, 3, 4, 5, 6, 7, 8, 8, 9])

In [2]:
import numpy as np
a=[[1,2,3],[4,5,6]]
np.array(a) # 2d


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.ndim
a.shape
a.size
a.dtype
a.itemsize

4

In [10]:
import numpy as np
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
#Reshape
n=np.arange(16).reshape(4,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
# random
s=np.random.randint(0,20,size=(3,5))
s

array([[11,  9,  1, 11, 11],
       [15,  7,  1, 10,  6],
       [12, 18, 18,  8,  0]])

In [19]:
import numpy as np
data=np.linspace(0,2,10)
data

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [21]:
#Resize
import numpy as np
data=np.linspace(0,5,20)
data.resize(4,5)
data

array([[0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158],
       [1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105],
       [2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053],
       [3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ]])

# Built in Functions
- ones 
- zeros

In [22]:
import numpy as np
data=np.ones((4,3)) # it will return float values...
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
import numpy as np
data=np.zeros((4,3)) # it will return float values...
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
import numpy as np
data=np.ones((4,3),int) # it will return float values...
data

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
# V-stack
n=np.ones([4,4],int)
#n
np.vstack([n,8*n])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [31]:
# H-Stack
import numpy as np
n=np.ones([5,6],int)
n
np.hstack([n,2*n])

array([[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]])

# Operators

In [36]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([0,92,3,7,6])
print(n+n1)
print(n-n1)
print(n*n1)
print(n**n1) #-->1**0=1, 2**9=512

[ 1 11  6 11 11]
[ 1 -7  0 -3 -1]
[ 0 18  9 28 30]
[    1   512    27 16384 15625]


# BODMAS
- Brackets of division
- Mul
- Add
- Sub

In [37]:
# Dot: Return the dot product of 2 vectors
n=np.array([1,2,3,4,5])
n1=np.array([6,7,8,9,5])
n.dot(n1)


105

In [39]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([n,n**3])
n1

array([[  1,   2,   3,   4,   5],
       [  1,   8,  27,  64, 125]])

In [40]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([n,pow(n,3)])
n1

array([[  1,   2,   3,   4,   5],
       [  1,   8,  27,  64, 125]])

# Transpose
- T--> Attribute for transpose
- transpose()

In [44]:
import numpy as np
n=np.array([[1,2,3,4,5],[0,9,8,7,6]])
n.T

array([[1, 0],
       [2, 9],
       [3, 8],
       [4, 7],
       [5, 6]])

In [45]:
n=np.array([[1, 0],
       [2, 9],
       [3, 8],
       [4, 7],
       [5, 6]])
n.T

array([[1, 2, 3, 4, 5],
       [0, 9, 8, 7, 6]])

In [46]:
import numpy as np
n=np.array([[1,2,3,4,5],[0,9,8,7,6]])
n.transpose()

array([[1, 0],
       [2, 9],
       [3, 8],
       [4, 7],
       [5, 6]])

#  Array datatype conversion
- dtype()-->it can find the list of values belongs to which type
- astype()-->it can perform type conversion

In [48]:
import numpy as np
n=np.array([1,3,5,7,9])
n.astype(str)
n.dtype

dtype('int32')

In [53]:
import numpy as np
n=np.array([1.5,2.3,5,7,8])
n
n.astype(int)
n.dtype

dtype('float64')

In [59]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
print(data.max())
print(data.min())
print(data.mean())
print(data.std())

[[14  4  3]
 [ 5 12  2]
 [ 6 13 11]
 [13  0  3]]
14
0
7.166666666666667
4.844813951249544
